import { Service, ServiceCategory, Testimonial, StatItem, Order } from "./types";

export const CATEGORIES: { slug: ServiceCategory; name: string; icon: string; desc: string }[] = [
  {
    slug: "education",
    name: "Education Services",
    icon: "GraduationCap",
    desc: "JAMB, WAEC, NECO registration, school projects and exam PINs",
  },
  {
    slug: "identity",
    name: "Identity & Documents",
    icon: "FileUser",
    desc: "NIN enrollment, Birth Certificates, Affidavits, and Marriage registration",
  },
  {
    slug: "nysc",
    name: "NYSC Services",
    icon: "Briefcase",
    desc: "NYSC registration, mobilization, corrections, and general documentation",
  },
  {
    slug: "business",
    name: "Business Services",
    icon: "Building2",
    desc: "CAC registrars, Corporate TIN, SCUML, and official corporate documents",
  },
  {
    slug: "travel",
    name: "Travel & Immigration",
    icon: "Plane",
    desc: "International passport, visa applications, and Driver's Licence services",
  },
  {
    slug: "property",
    name: "Property & Legal",
    icon: "Home",
    desc: "Land & housing registration and House to Rent finder assistants",
  },
  {
    slug: "employment",
    name: "Employment & Career",
    icon: "FileText",
    desc: "Recruitment applications, Job registrations, and professional CV writing",
  },
  {
    slug: "printing",
    name: "Printing & Media",
    icon: "Printer",
    desc: "High quality press prints, digital frame enlargements, and photo media",
  },
  {
    slug: "digital",
    name: "Digital & Recharge",
    icon: "Smartphone",
    desc: "Instant high-speed mobile data subscription and swift airtime top-ups",
  },
  {
    slug: "gadgets",
    name: "Gadget Store",
    icon: "Laptop",
    desc: "Premium quality laptops, smartphones, essential accessories, and smart devices",
  },
];

export const SERVICES: Service[] = [
  // EDUCATION SERVICES
  {
    id: "jamb-reg",
    name: "JAMB Direct Registration",
    description: "Get your JAMB registration processed by accredited agents without queuing.",
    category: "education",
    priceRaw: 7500,
    estimatedTime: "24 Hours",
    popular: true,
    fields: [
      { name: "fullName", label: "Full Name (Surname First)", placeholder: "e.g., Alao Babatunde Yusuf", type: "text", required: true },
      { name: "profileCode", label: "JAMB Profile Code", placeholder: "e.g., 5501928391", type: "text", required: true },
      { name: "phoneNumber", label: "NIN Registered Phone Number", placeholder: "e.g., 08012345678", type: "tel", required: true },
      { name: "choices", label: "Preferred Institution & Course Choices", placeholder: "e.g., 1st Choice: Unilag (Medicine), 2nd Choice...", type: "textarea", required: true },
    ],
  },
  {
    id: "jamb-result",
    name: "JAMB Result Slip Printing",
    description: "Official color print-out of your JAMB exam credentials with standard passport watermark.",
    category: "education",
    priceRaw: 2500,
    estimatedTime: "1 Hour",
    fields: [
      { name: "regNumber", label: "JAMB Registration Number", placeholder: "e.g., 202638491039CF", type: "text", required: true },
      { name: "examYear", label: "Examination Year", placeholder: "e.g., 2026", type: "select", required: true, options: ["2026", "2025", "2024", "2023", "2022"] },
    ],
  },
  {
    id: "admission-letter",
    name: "Jamb Admission Letter Printing",
    description: "Instant processing and retrieval of your original JAMB admission letters required for clearance.",
    category: "education",
    priceRaw: 3500,
    estimatedTime: "2 Hours",
    fields: [
      { name: "regNumber", label: "JAMB Registration Number", placeholder: "e.g., 202638491039CF", type: "text", required: true },
      { name: "institution", label: "Admitted Institution", placeholder: "e.g., University of Ibadan", type: "text", required: true },
    ],
  },
  {
    id: "change-institution",
    name: "Jamb Change Change of Institution",
    description: "Correction of choice institution or data uploads after release of UTME scores.",
    category: "education",
    priceRaw: 4500,
    estimatedTime: "12 Hours",
    fields: [
      { name: "regNumber", label: "JAMB Registration Number", placeholder: "e.g., 202638491039CF", type: "text", required: true },
      { name: "newInstitution", label: "New Preferred Institution", placeholder: "e.g., UNN", type: "text", required: true },
      { name: "newCourse", label: "New Course Choice", placeholder: "e.g., Computer Science", type: "text", required: true },
    ],
  },
  {
    id: "change-course",
    name: "Jamb Change of Course",
    description: "Align your profile with standard department quotas by submitting change of course requests.",
    category: "education",
    priceRaw: 4500,
    estimatedTime: "12 Hours",
    fields: [
      { name: "regNumber", label: "JAMB Registration Number", placeholder: "e.g., 202638491039CF", type: "text", required: true },
      { name: "newCourse", label: "New Desired Course", placeholder: "e.g., Electrical Engineering", type: "text", required: true },
    ],
  },
  {
    id: "waec-reg",
    name: "WAEC Registration (Internal/External)",
    description: "Hassle-free WAEC registration for candidates. Form loading, subject matching, and center assignments.",
    category: "education",
    priceRaw: 27500,
    estimatedTime: "48 Hours",
    fields: [
      { name: "fullName", label: "Candidate Full Name", placeholder: "e.g., Emeka Obi", type: "text", required: true },
      { name: "nin", label: "National Identification Number (NIN)", placeholder: "e.g., 12345678901", type: "text", required: true },
      { name: "subjects", label: "Selected 9 Subjects", placeholder: "e.g., English, Maths, Civic Education, Physics, Chemistry...", type: "textarea", required: true },
    ],
  },
  {
    id: "neco-reg",
    name: "Apply For NECO Registration",
    description: "Submit details to enroll in the upcoming National Examinations Council (NECO) examination cycles.",
    category: "education",
    priceRaw: 24000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "fullName", label: "Candidate Full Name", placeholder: "e.g., Fatima Aminu", type: "text", required: true },
      { name: "subjects", label: "9 Subjects to Enroll", placeholder: "e.g., English, Mathematics, Biology, Chemistry, Agricultural Science...", type: "textarea", required: true },
    ],
  },
  {
    id: "gce-reg",
    name: "Apply For WAEC/NECO GCE Registration",
    description: "Direct registrations for private external candidates (GCE) including preferred exam location selection.",
    category: "education",
    priceRaw: 28000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "examType", label: "Select GCE Exam", placeholder: "", type: "select", required: true, options: ["WAEC Private Candidate (GCE)", "NECO Private Candidate (GCE)"] },
      { name: "state", label: "Preferred Exam Center State", placeholder: "e.g., Lagos State", type: "text", required: true },
      { name: "subjects", label: "Core Academic Subjects List", placeholder: "List up to 9 subjects", type: "textarea", required: true },
    ],
  },
  {
    id: "purchase-pin",
    name: "Purchase Examination Card PIN",
    description: "Get instant PIN/Serials to access WAEC, NECO, or NABTEB results online. Generated instantly on purchase.",
    category: "education",
    priceRaw: 4000,
    estimatedTime: "Instant Retrieval",
    popular: true,
    fields: [
      { name: "cardType", label: "Result Checker Card Brand", placeholder: "", type: "select", required: true, options: ["WAEC Scratch Card Token", "NECO Token", "NABTEB Scratch Card PIN", "JAMB e-PIN (UTME)"] },
      { name: "emailRecipient", label: "Active Email Address (PIN Delivery Destination)", placeholder: "e.g., candidate@gmail.com", type: "email", required: true },
    ],
  },
  {
    id: "post-utme",
    name: "Post-UTME Registration Portal Setup",
    description: "We handle your preferred university's secondary application uploads, screening forms, and slip prints.",
    category: "education",
    priceRaw: 5000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "institutionName", label: "University/Polytechnic Name", placeholder: "e.g., University of Benin", type: "text", required: true },
      { name: "jambReg", label: "JAMB Registration Number", placeholder: "e.g., 2026938481", type: "text", required: true },
      { name: "olevelDetails", label: "O-level Result Reference (e.g. WAEC 2025)", placeholder: "e.g., WAEC 2025 - Exam No: 412039...", type: "textarea", required: true },
    ],
  },
  {
    id: "scholarship-reg",
    name: "National & Intentional Scholarship Registration",
    description: "Application packaging for federal, state-sponsored, or corporate scholarship funds.",
    category: "education",
    priceRaw: 6000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "scholarshipName", label: "Scholarship Scheme", placeholder: "e.g., Shell Scholarship, Federal Bilateral award", type: "text", required: true },
      { name: "schoolLevel", label: "Academic Level", placeholder: "e.g., Undergraduate Year 2", type: "text", required: true },
      { name: "gpa", label: "CGPA / Average Score", placeholder: "e.g., 4.54 / 5.00", type: "text", required: true },
    ],
  },
  {
    id: "inter-school",
    name: "Apply For International School Application Form",
    description: "Form submissions, transcript request forwarding, and document packing for international admissions.",
    category: "education",
    priceRaw: 15000,
    estimatedTime: "3 - 5 Days",
    fields: [
      { name: "targetCountry", label: "Destination Country", placeholder: "e.g., United Kingdom, Canada, USA", type: "text", required: true },
      { name: "courseOfStudy", label: "Desired Program", placeholder: "e.g., MSc Global Health Solutions", type: "text", required: true },
      { name: "currentDegree", label: "Current Degree / Qualification", placeholder: "e.g., BSc Nursing", type: "text", required: true },
    ],
  },
  {
    id: "assignments",
    name: "School Assignments Assistant",
    description: "Research guidance and references formatting support for complex college/university assignments.",
    category: "education",
    priceRaw: 3000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "subjectTitle", label: "Assignment Title / Subject", placeholder: "e.g., Constitutional Law: Human Rights Act", type: "text", required: true },
      { name: "academicLevel", label: "Educational Level", placeholder: "e.g., Tertiary Year 3", type: "text", required: true },
      { name: "instructions", label: "Detailed Instructions / Requirements", placeholder: "Paste assignment questions or description here...", type: "textarea", required: true },
    ],
  },
  {
    id: "projects",
    name: "Final Year Projects Material",
    description: "Professional research consultancy, literature review formulation, data analysis, and documentation proofreading.",
    category: "education",
    priceRaw: 35000,
    estimatedTime: "7 - 14 Days",
    fields: [
      { name: "department", label: "Department / Course of Study", placeholder: "e.g., Business Administration", type: "text", required: true },
      { name: "projectTopic", label: "Proposed / Approved Project Topic", placeholder: "e.g., The Impact of Electronic Payments on SME Growth", type: "text", required: true },
      { name: "currentChapter", label: "Required Phase/Chapters", placeholder: "e.g., Chapter 1 to 3 Research Proposal", type: "text", required: true },
    ],
  },

  // IDENTITY & DOCUMENT SERVICES
  {
    id: "nin-enroll",
    name: "NIN Services",
    description: "Pre-enrollment, official schedule booking, name correction requests, or date of birth modifications on NIMC portal.",
    category: "identity",
    priceRaw: 5500,
    estimatedTime: "24 Hours",
    popular: true,
    fields: [
      { name: "requestType", label: "Service Request Type", placeholder: "", type: "select", required: true, options: ["Fresh NIN Enrollment Slip", "NIN Name Correction", "NIN Phone Number Linkage", "Re-print Lost NIMC slip"] },
      { name: "currentDetails", label: "Full Personal Details (NIMC format)", placeholder: "e.g., Name, Date of Birth, State of Origin...", type: "textarea", required: true },
    ],
  },
  {
    id: "npc-birth",
    name: "NPC Birth Certificate Processing",
    description: "Secure original Birth Certificates or official Age Declarations from the National Population Commission (NPC).",
    category: "identity",
    priceRaw: 8000,
    estimatedTime: "3 Days",
    fields: [
      { name: "fullName", label: "Applicant's Full Name", placeholder: "Full Name", type: "text", required: true },
      { name: "dob", label: "Date of Birth", placeholder: "DD/MM/YYYY", type: "text", required: true },
      { name: "parentNames", label: "Parent Details (Mother and Father Full Names)", placeholder: "e.g., Father: James Obi, Mother: Mary Obi", type: "textarea", required: true },
      { name: "stateOfBirth", label: "State and LGA of Birth", placeholder: "e.g., Enugu State, Nsukka LGA", type: "text", required: true },
    ],
  },
  {
    id: "court-affidavit",
    name: "Court Affidavit Filing",
    description: "Affidavits for Loss of Items, Declaration of Age, Correction of Name, or Change of Ownership officially notarized.",
    category: "identity",
    priceRaw: 4500,
    estimatedTime: "24 Hours",
    fields: [
      { name: "affidavitType", label: "Type of Affidavit Needed", placeholder: "", type: "select", required: true, options: ["Correction & Declaration of Name", "Loss of Document / Sim Card", "Age Declaration Support", "Other Legal Affidavits"] },
      { name: "statement", label: "Affidavit Fact Statement / Details", placeholder: "e.g. Specify correct name vs or details of lost items...", type: "textarea", required: true },
    ],
  },
  {
    id: "marriage-cert",
    name: "Marriage Certificate Assistance",
    description: "Assistance with official Ministry of Interior registry marriage applications and certificate document files.",
    category: "identity",
    priceRaw: 45000,
    estimatedTime: "7 Days",
    fields: [
      { name: "husbandName", label: "Husband's Full Name", placeholder: "Husband Name", type: "text", required: true },
      { name: "wifeName", label: "Wife's Full Name", placeholder: "Wife's Maiden Name", type: "text", required: true },
      { name: "marriageDate", label: "Proposed Marriage Date", placeholder: "e.g., August 12, 2026", type: "text", required: true },
    ],
  },
  {
    id: "police-report",
    name: "Police Report / Character Clearance",
    description: "Facilitate processing of police character checks or formal police documentation for loss of properties.",
    category: "identity",
    priceRaw: 12000,
    estimatedTime: "3 Days",
    fields: [
      { name: "fullName", label: "Full Legal Name", placeholder: "Full Name", type: "text", required: true },
      { name: "reason", label: "Reason for Clearance/Report", placeholder: "e.g. International Job, Loss of Vehicle License...", type: "textarea", required: true },
    ],
  },
  {
    id: "security-form",
    name: "Nigerian Security Form Registration",
    description: "Online filling for security and paramilitary recruitment forms (Police, Army, Airforce, Navy, NSCDC, etc).",
    category: "identity",
    priceRaw: 4000,
    estimatedTime: "12 Hours",
    fields: [
      { name: "agencyName", label: "Paramilitary/Military Agency Name", placeholder: "e.g., Nigerian Army", type: "text", required: true },
      { name: "appId", label: "Application Portal ID/Credentials (if any)", placeholder: "Username or application reference code", type: "text", required: false },
      { name: "requirements", label: "Specific Educational/Medical Details", placeholder: "List your height, chest width, qualifications...", type: "textarea", required: true },
    ],
  },
  {
    id: "newspaper-pub",
    name: "Apply For Newspaper Publication",
    description: "Submit name changes, loss of documents, or official public notices for publication in major national daily newspapers.",
    category: "identity",
    priceRaw: 8500,
    estimatedTime: "24 Hours",
    popular: true,
    fields: [
      { name: "fullName", label: "Applicant's Full Name", placeholder: "Enter your current full legal name", type: "text", required: true },
      { name: "publicationType", label: "Type of Publication Notice", placeholder: "", type: "select", required: true, options: ["Change of Name", "Loss of Documents", "Public Announcement", "Age Declaration Support"] },
      { name: "preferredNewspaper", label: "Preferred National Daily Newspaper", placeholder: "", type: "select", required: true, options: ["The Punch", "Vanguard Newspaper", "The Guardian", "The Nation", "Daily Trust"] },
      { name: "details", label: "Publication Content / Notice Text", placeholder: "Provide the exact text or specify former/new name, affidavit details, etc.", type: "textarea", required: true },
    ],
  },

  // NYSC SERVICES
  {
    id: "nysc-reg",
    name: "NYSC Portal Direct Registration",
    description: "Error-free mobilization filing, biometric schedules, green card printing support.",
    category: "nysc",
    priceRaw: 6500,
    estimatedTime: "24 Hours",
    popular: true,
    fields: [
      { name: "fullName", label: "Full Name (as registered with Institution)", placeholder: "First Middle Surname", type: "text", required: true },
      { name: "callupNumber", label: "Institution Matric/JAMB Reg Number", placeholder: "JAMB or School Matric Number", type: "text", required: true },
      { name: "institution", label: "Graduating University/Polytechnic", placeholder: "e.g., Federal Poly Nekede", type: "text", required: true },
      { name: "bloodGroup", label: "Blood Group & Genotype", placeholder: "e.g., O+ / AA", type: "text", required: true },
    ],
  },
  {
    id: "nysc-remobilization",
    name: "NYSC Remobilization Setup",
    description: "For corps members who abandoned their service sessions, assisting with reinstatement approvals.",
    category: "nysc",
    priceRaw: 8000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "state", label: "State of Initial Deployment", placeholder: "e.g., Rivers State", type: "text", required: true },
      { name: "batch", label: "Original Service Batch/Year", placeholder: "e.g., Batch B 2024", type: "text", required: true },
      { name: "reason", label: "Reason for Remobilization", placeholder: "Brief explanation of health or personal issues...", type: "textarea", required: true },
    ],
  },
  {
    id: "nysc-correction",
    name: "NYSC Profile Detail Correction",
    description: "Official letters or digital appeals for Date of Birth, Spelling of Name, or Course of Study on NYSC dashboard.",
    category: "nysc",
    priceRaw: 4000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "email", label: "NYSC Portal Login Email", placeholder: "e.g., corpsmember@google.com", type: "email", required: true },
      { name: "incorrectDetail", label: "Specify Incorrect Detail on Profile", placeholder: "What is currently there?", type: "text", required: true },
      { name: "correctionNeeded", label: "Specify Correct Target Value", placeholder: "What should be there?", type: "text", required: true },
    ],
  },
  {
    id: "nysc-documentation",
    name: "NYSC Relocation & Letter uploads",
    description: "Facilitate document uploads, medical report certifications, or concessionary posting approvals.",
    category: "nysc",
    priceRaw: 5000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "targetState", label: "Preferred State of Relocation", placeholder: "e.g., Lagos, Abuja", type: "text", required: true },
      { name: "relocationReason", label: "Grounds for Relocation", placeholder: "e.g., Marital (Husband location) or Medical", type: "textarea", required: true },
    ],
  },

  // BUSINESS SERVICES
  {
    id: "cac-business",
    name: "CAC Business Name Registration",
    description: "Official registration with Name Reservation, Filing Fee payments, and Certificates delivery from Corporate Affairs Commission.",
    category: "business",
    priceRaw: 22000,
    estimatedTime: "7 - 10 Days",
    popular: true,
    fields: [
      { name: "businessName1", label: "First Option Business Name", placeholder: "e.g., MYSOLUTION CYBER SERVICES", type: "text", required: true },
      { name: "businessName2", label: "Second Option Business Name", placeholder: "e.g., MYSOLUTION TECH HUB", type: "text", required: true },
      { name: "proprietorName", label: "Proprietor Full Name", placeholder: "Full Legal Name", type: "text", required: true },
      { name: "address", label: "Physical Business Address", placeholder: "Plot Number, Street name, State", type: "textarea", required: true },
    ],
  },
  {
    id: "tin-reg",
    name: "Joint Tax Identification Number (TIN)",
    description: "Get a corporate TIN for your business name or limited company with Federal Inland Revenue Service (FIRS).",
    category: "business",
    priceRaw: 7500,
    estimatedTime: "3 Days",
    fields: [
      { name: "registeredName", label: "Registered Business/Enterprise Name", placeholder: "Exact registered CAC name", type: "text", required: true },
      { name: "rcNo", label: "RC or BN Registration Number", placeholder: "e.g., BN2026849", type: "text", required: true },
      { name: "natureOfBusiness", label: "Primary Nature of Business", placeholder: "e.g. IT services, Trading, Agriculture", type: "text", required: true },
    ],
  },
  {
    id: "scuml-reg",
    name: "EFCC SCUML Registration Certificate",
    description: "Special Control Unit against Money Laundering (SCUML) certification assistance for designated non-financial businesses.",
    category: "business",
    priceRaw: 35000,
    estimatedTime: "10 - 14 Days",
    fields: [
      { name: "businessName", label: "Corporate Business Name", placeholder: "Corporate Name", type: "text", required: true },
      { name: "directors", label: "Names of Business Directors / Trustees", placeholder: "Full Names of core staff...", type: "textarea", required: true },
    ],
  },
  {
    id: "business-docs",
    name: "Business Partnership & Legal Agreements",
    description: "Structured corporate templates representing standard partner terms, non-disclosures (NDA), and operational drafts.",
    category: "business",
    priceRaw: 12000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "party1", label: "First Party / Client Name", placeholder: "Who is drafting?", type: "text", required: true },
      { name: "party2", label: "Second Party / Partner Name", placeholder: "Who is signing?", type: "text", required: true },
      { name: "scope", label: "Operational Scope & Key Terms", placeholder: "Describe the trade agreement or project details...", type: "textarea", required: true },
    ],
  },

  // TRAVEL & IMMIGRATION
  {
    id: "passport-processing",
    name: "Apply For Nigerian International Passport Processing & Renewal",
    description: "Standard portal filing, payment processing, biometric schedules booking for both 32-page and 64-page booklets.",
    category: "travel",
    priceRaw: 65000,
    estimatedTime: "7 - 14 Days",
    popular: true,
    fields: [
      { name: "fullName", label: "Full Name (In exact NIN alignment)", placeholder: "Surname First", type: "text", required: true },
      { name: "nin", label: "NIN Number", placeholder: "11-digit number", type: "text", required: true },
      { name: "stateOffice", label: "State of biometric capture enrollment office", placeholder: "e.g., Lagos Alausa Office, Enugu Office", type: "text", required: true },
      { name: "bookletType", label: "Select Passport Package", placeholder: "", type: "select", required: true, options: ["5-Year Validity (32 Pages)", "10-Year Validity (64 Pages)"] },
    ],
  },
  {
    id: "visa-processing",
    name: "Visa Appointment & Application Assistance",
    description: "Support filling DS-160 forms, visa fee payments, biometric appointment bookings for travel planning.",
    category: "travel",
    priceRaw: 35000,
    estimatedTime: "3 - 5 Days",
    fields: [
      { name: "country", label: "Target Destination Country", placeholder: "e.g., United Kingdom, Germany, South Africa", type: "text", required: true },
      { name: "visaType", label: "Type of Visa Required", placeholder: "Student study, tourist visitor, business", type: "text", required: true },
      { name: "financialSponsor", label: "Financial Sponsor Information", placeholder: "Self-sponsored, family relative, or scholarship fund...", type: "textarea", required: true },
    ],
  },
  {
    id: "drivers-license",
    name: "Driver's Licence Registration (Fresh)",
    description: "Booking driving school tests, completing VIO screenings, and scheduling FRSC capture appointments.",
    category: "travel",
    priceRaw: 22000,
    estimatedTime: "10 Days",
    fields: [
      { name: "fullName", label: "Applicant's Full Name", placeholder: "Legal name", type: "text", required: true },
      { name: "bloodGroup", label: "Blood Group", placeholder: "e.g., O+", type: "text", required: true },
      { name: "address", label: "Home Address", placeholder: "Home address for driver record", type: "textarea", required: true },
    ],
  },
  {
    id: "license-renewal",
    name: "Driver's Licence Renewal",
    description: "Hassle-free FRSC renewal portal submission. Bypasses physical physical tests for experienced drivers with records.",
    category: "travel",
    priceRaw: 18000,
    estimatedTime: "3 Days",
    fields: [
      { name: "licenseNo", label: "Drivers Licence Serial Number", placeholder: "e.g., ABG10293JDW8", type: "text", required: true },
      { name: "fullName", label: "Full Registered Name", placeholder: "Name", type: "text", required: true },
    ],
  },

  // PROPERTY & LEGAL SERVICES
  {
    id: "land-reg",
    name: "Land Registration Service",
    description: "Filing and preparing Deeds of Transfer or registering global Certificates of Ownership (C of O) drafts.",
    category: "property",
    priceRaw: 55000,
    estimatedTime: "14 - 30 Days",
    fields: [
      { name: "buyerName", label: "Buyer / Current Owner Name", placeholder: "Buyer Full Name", type: "text", required: true },
      { name: "sellerName", label: "Seller / Previous Owner Name", placeholder: "First Owner Name", type: "text", required: true },
      { name: "landSize", label: "Land size & Location Details", placeholder: "e.g., Plot 14, Phase 2 Estate, Trans Ekulu, Enugu. Size: 600sqm", type: "textarea", required: true },
    ],
  },
  {
    id: "property-reg",
    name: "Commercial Property Registration Services",
    description: "Registering commercial structures, apartments, or warehouses on central municipal billing codes and tax catalogs.",
    category: "property",
    priceRaw: 45000,
    estimatedTime: "10 Days",
    fields: [
      { name: "propertyName", label: "Property / Complex Name", placeholder: "e.g., Solution Plaza", type: "text", required: true },
      { name: "stateLga", label: "State and Local Government Area", placeholder: "e.g., Abuja Municipal Area Council", type: "text", required: true },
    ],
  },
  {
    id: "house-rent",
    name: "House to Rent Finder Assistance",
    description: "Consult with verified local real estate brokers to locate houses matching your preferred budgets.",
    category: "property",
    priceRaw: 5000,
    estimatedTime: "2-3 Days",
    fields: [
      { name: "houseType", label: "Type of Apartment Required", placeholder: "e.g., 2 Bedroom Flat, Self Contain, Office Space", type: "text", required: true },
      { name: "maxBudget", label: "Maximum Budget per Annum (NGN)", placeholder: "e.g., 1,500,000", type: "text", required: true },
      { name: "preferredLocation", label: "Preferred Area/Neighborhoods", placeholder: "e.g., Lekki Phase 1, Yaba, Ikeja", type: "textarea", required: true },
    ],
  },

  // EMPLOYMENT SERVICES
  {
    id: "job-opp",
    name: "Federal / State Recruitment Applications",
    description: "We help map qualifications and load candidate credentials into federal commissions profiles.",
    category: "employment",
    priceRaw: 3500,
    estimatedTime: "12 Hours",
    fields: [
      { name: "portalName", label: "Target Recruitment Scheme/Commission", placeholder: "e.g., Civil Service Commission, Customs, NDLEA", type: "text", required: true },
      { name: "credentials", label: "Primary Qualifications (Degree, GPA, Year of Grad)", placeholder: "Specify level of education", type: "textarea", required: true },
    ],
  },
  {
    id: "cv-writing",
    name: "Professional Resume & CV Remodeling",
    description: "Upgrade your profile with ATS-compliant resume drafts, premium cover letters, and optimized LinkedIn summaries.",
    category: "employment",
    priceRaw: 8000,
    estimatedTime: "2 Days",
    popular: true,
    fields: [
      { name: "currentJob", label: "Current Job Title / Professional Field", placeholder: "e.g., Entry-level Accountant", type: "text", required: true },
      { name: "experienceLevel", label: "Years of Experience", placeholder: "e.g., 2 years", type: "text", required: true },
      { name: "skills", label: "Skills & Education Background", placeholder: "List main achievements, degree, and technical skills...", type: "textarea", required: true },
    ],
  },
  {
    id: "recruitment-app",
    name: "Active Recruiters Email Application Campaign",
    description: "Targeted outbound letters delivering candidate profiles directly to premium private agencies in Lagos/Abuja.",
    category: "employment",
    priceRaw: 6000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "targetSectors", label: "Preferred Industries / Sectors", placeholder: "e.g. Banking, Oil & Gas, Fintech", type: "text", required: true },
      { name: "targetRoles", label: "Target Role Titles", placeholder: "e.g. Junior Developer, Sales Executive", type: "text", required: true },
    ],
  },

  // PRINTING & MEDIA
  {
    id: "print-press",
    name: "Bulk Printing & Flyers Press",
    description: "Premium flyers, stickers, calendars, greeting brochures, or official business custom stationery.",
    category: "printing",
    priceRaw: 15000, // starting
    estimatedTime: "3 Days",
    fields: [
      { name: "printMedium", label: "Medium / Paper Specification", placeholder: "", type: "select", required: true, options: ["A4 Standard Flyers (130gsm/A4)", "Business Brand Cards (Matte card)", "Exhibition Banners (Flex)", "Custom Stickers"] },
      { name: "quantity", label: "Required Quantity", placeholder: "e.g., 500 copies", type: "text", required: true },
      { name: "details", label: "Draft Layout Text & Design details", placeholder: "Describe fonts, text to display, colors...", type: "textarea", required: true },
    ],
  },
  {
    id: "frame-enlarge",
    name: "Frame Enlargement Services",
    description: "Sleek wooden border laminations magnifying portrait snaps or memorable family wedding photo packages.",
    category: "printing",
    priceRaw: 12000,
    estimatedTime: "48 Hours",
    fields: [
      { name: "frameSize", label: "Frame Dimension Choice", placeholder: "", type: "select", required: true, options: ["12x16 Inches Frame", "16x20 Inches Frame", "20x24 Inches Frame", "24x36 Inches Large Exhibition Frame"] },
      { name: "borderStyle", label: "Border Wood Wrap & Color Option", placeholder: "", type: "select", required: true, options: ["Minimalist Onyx Black Edge", "Regal Classic Gold Border", "Natural Organic Walnut Wood"] },
    ],
  },

  // DIGITAL SERVICES
  {
    id: "airtime-top",
    name: "Automated Swift Airtime Recharge",
    description: "Send airtime instantly to any Nigerian mobile network provider with discount allowances.",
    category: "digital",
    priceRaw: 1000,
    estimatedTime: "Instant Delivery",
    fields: [
      { name: "network", label: "Network Provider", placeholder: "", type: "select", required: true, options: ["MTN", "Airtel", "Glo", "9mobile"] },
      { name: "phoneNo", label: "Recipient Phone Number", placeholder: "e.g., 08030001122", type: "tel", required: true },
      { name: "amount", label: "Recharge Value Amount (NGN)", placeholder: "e.g., 2000", type: "number", required: true },
    ],
  },
  {
    id: "data-sub",
    name: "High-Speed SME Mobile Data Plans",
    description: "Purchase premium monthly data (30-day validity) directly on major Nigerian networks (MTN, Glo, Airtel).",
    category: "digital",
    priceRaw: 1200,
    estimatedTime: "Instant Retrieval",
    popular: true,
    fields: [
      { name: "network", label: "Mobile Network Plan", placeholder: "", type: "select", required: true, options: ["MTN 1GB (30 days) - ₦350", "MTN 5GB (30 days) - ₦1500", "Airtel 2GB (30 days) - ₦700", "Airtel 10GB (30 days) - ₦2800", "Glo 3GB (30 days) - ₦850", "Glo 15GB (30 days) - ₦3200"] },
      { name: "phoneNo", label: "Beneficiary Mobile Number", placeholder: "e.g., 09055442211", type: "tel", required: true },
    ],
  },

  // GADGET STORE
  {
    id: "phone-store",
    name: "Affordable Smartphones Purchase Request",
    description: "Inquire or purchase top tier original Nigeria warranty mobile devices (Infinix, Tecno, Samsung, Xiaomi, iPhone).",
    category: "gadgets",
    priceRaw: 145000, // placeholder average
    estimatedTime: "1 - 3 Days Delivery",
    fields: [
      { name: "brandModel", label: "Target Phone Brand & Model", placeholder: "e.g., Redmi Note 13, iPhone 14 Pro, Samsung Galaxy A35", type: "text", required: true },
      { name: "specifications", label: "Configuration Preference (RAM, Storage, Color)", placeholder: "e.g., 8GB RAM + 256GB Storage, Midnight Navy", type: "text", required: true },
    ],
  },
  {
    id: "laptop-store",
    name: "Premium Laptops Store Portfolio",
    description: "Register request for high-durability school-friendly or office-centered computers (HP, Dell, Lenovo, MacBook).",
    category: "gadgets",
    priceRaw: 290000,
    estimatedTime: "1 - 3 Days Delivery",
    fields: [
      { name: "useCase", label: "Main Intended Laptop Use Case", placeholder: "", type: "select", required: true, options: ["Programming & Software Development", "College Assignments & General Office work", "Graphic Design & Heavy Media rendering", "High Performance Gaming"] },
      { name: "laptopBrand", label: "Preferred Laptop Brand / Budget", placeholder: "e.g., HP Core i5, 16GB RAM, SSD", type: "text", required: true },
    ],
  },
  {
    id: "gadget-accessories",
    name: "Mobile & Laptop Essential Accessories",
    description: "High durability power banks, wireless Bluetooth ear-pieces, heavy duty protective covers, and rapid chargers.",
    category: "gadgets",
    priceRaw: 15000,
    estimatedTime: "24 Hours",
    fields: [
      { name: "accessoryNeeded", label: "Choose Accessories Required", placeholder: "e.g. Oraimo 20000mAh Power Bank, Type-C Rapid Cord", type: "text", required: true },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "#WP20273",
    serviceId: "purchase-pin",
    serviceName: "Purchase Examination Card PIN",
    category: "education",
    userName: "owohpaulchinedum",
    userEmail: "owohpaulchinedum@gmail.com",
    userPhone: "08034567890",
    status: "completed",
    orderDate: "2026-06-13, 03:44 PM",
    amount: 4000,
    paymentMethod: "Paystack",
    paymentStatus: "paid",
    details: {
      cardType: "WAEC Scratch Card Token",
      emailRecipient: "owohpaulchinedum@gmail.com",
    },
    generatedData: {
      pin: "9012-4859-1029-3849",
      serial: "WRN2026859348",
      note: "WAEC PIN generated successfully! Valid for 5 result check usage sessions on the official waecdirect.org portal.",
    },
  },
  {
    id: "#CAC9483",
    serviceId: "cac-business",
    serviceName: "CAC Business Name Registration",
    category: "business",
    userName: "Ngozi Chukwu",
    userEmail: "ngozi.ventures@firs.com.ng",
    userPhone: "08129384829",
    status: "processing",
    orderDate: "2026-06-12, 10:15 AM",
    amount: 22000,
    paymentMethod: "Bank Transfer",
    paymentStatus: "paid",
    details: {
      businessName1: "NGOZI CHUKWU TRADING ENTERPRISES",
      businessName2: "NGOZI CHUKWU GLOBAL LOGISTICS",
      proprietorName: "Ngozi Amara Chukwu",
      address: "No 12 Ogui Road, Enugu, Enugu State",
    },
    generatedData: {
      note: "CAC name reservation approved: NGOZI CHUKWU TRADING ENTERPRISES has been reserved. Documents currently with registration agents for final filing.",
    },
  },
  {
    id: "#NIN1129",
    serviceId: "nin-enroll",
    serviceName: "NIN Services",
    category: "identity",
    userName: "Shehu Musa",
    userEmail: "shehumusa@yahoo.com",
    userPhone: "09012233445",
    status: "completed",
    orderDate: "2026-06-11, 01:22 PM",
    amount: 5500,
    paymentMethod: "Card",
    paymentStatus: "paid",
    details: {
      requestType: "NIN Name Correction",
      currentDetails: "Current Name: Shehu Masu, Correction: Shehu Musa, DOB: 12/04/1998, NIN: 90238491039",
    },
    generatedData: {
      deliveredFile: "https://www.nimc.gov.ng/",
      note: "Correction submitted to NIMC mainframe. Verified slip ready! Slip PDF downloaded and sent to email destination.",
    },
  },
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: "test-1",
    name: "Dr. Chinyere Okafor",
    role: "Senior Lecturer, University of Nigeria",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200",
    rating: 5,
    content: "MYSOLUTION HUB handles all my academic and passport registrations. They are highly professional, error-free, and incredibly transparent. Buying exam PINs is instant!",
    location: "Nsukka, Enugu",
  },
  {
    id: "test-2",
    name: "Yusuf Babangida",
    role: "Proprietor, YB Agro-Allied Agencies",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200",
    rating: 5,
    content: "CAC Registration in Nigerian context is usually associated with delays, but MYSOLUTION HUB completed my business incorporation certificate in less than 8 days! Highly recommended.",
    location: "Kano State",
  },
  {
    id: "test-3",
    name: "Chioma Adebayo",
    role: "Ex-Corps Member (2025 Batch B)",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=200",
    rating: 5,
    content: "My NYSC registration form had critical spelling mistakes on the Senate list. Solutions Hub completed my direct correction quickly so I didn't miss my deployment batch.",
    location: "Lekki, Lagos",
  },
];

export const STATS: StatItem[] = [
  { value: "5,400+", numericValue: 5400, suffix: "+", label: "Satisfied Clients", description: "Successful candidate entries, business setups and passport clearance" },
  { value: "100+", numericValue: 100, suffix: "+", label: "Services Available", description: "All education, identity documentation, travel visa, or CAC services are cataloged" },
  { value: "24/7", numericValue: 24, suffix: "/7", label: "Active Support", description: "Our help Desk and dedicated WhatsApp assistant answer any query immediately" },
  { value: "99.2%", numericValue: 99.2, suffix: "%", label: "Success Rate", description: "Zero record loss, zero failed registration submissions over five active years" },
];

export const FAQ_ITEMS = [
  {
    question: "How do I receive my document uploads or purchased PINs?",
    answer: "PIN check codes (e.g. WAEC, NECO scratch cards) are instantly delivered directly to your email address and shown on screen upon registration checkout. For complex documents (like CAC Certificates or court affidavits), physical papers are sent via premium motor transport (GIGM/Peace Transport) while digitized PDFs are sent to your verified email address.",
  },
  {
    question: "Are payment protocols on MYSOLUTION HUB secure?",
    answer: "We support industry standard multi-channel payment procedures including Paystack, debit cards, and local instant bank transfers to ensure zero security leaks and maximum confirmation speed.",
  },
  {
    question: "Can I track the current state of my documentation request?",
    answer: "Absolutely! Every service checkout yields a unique Reference ID (e.g., #WP20273). Paste this reference key into the 'Order Tracker' on our homepage navigation console to monitor its real-time approval status and retrieve pin details instantly.",
  },
  {
    question: "What happens if there's an error in my NIN or JAMB bio-data details?",
    answer: "No alarms. Simply select our corrective categories ('NIN Correction' or 'NYSC Detail Correction') and specify what needs correction, and our database operators will file digital portal appeals directly with corresponding authorities on your behalf.",
  },
];
